### PR TITLE
Adding scriptBasePath extension property

### PR DESCRIPTION
**Pull request by pilak**
I guess there are some documentation lacking...
Adding this property permit of set a different project .js files path.

What do you think about it ?

### CODE REVIEW

**Comment by frederic-kneier** [comment]
Looks ok to me right now. I will have a better look soon and will merge the request if all is ok.

**Comment by frederic-kneier** [comment]
Hi @pilak . Sorry for the delay. I have added a comment to the changed files. Also please raise the version in "build.gradle" to 0.3.0.

**Comment by pilak** [comment]
Done... I pushed -f
But I realized that you said you added a comment to the changed file... does it mean in my branch ?

**Comment by frederic-kneier** [comment]
Yes. As far as I understand the npm run rule doesn't address actual javascript files but script blocks defined in package.json. So adding the scriptBasePath wouldn't apply to NodeJsPlugin.groovy:30

**Comment by pilak** [comment]
It would be better now :)

**Pull request merged**
